apiVersion: v1
kind: Pod
metadata:
  name: sriovpod1
  namespace: sriov-testing
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-network
spec:
  containers:
  - name: sriovpod1
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep 600000& wait"]
    image: registry.redhat.io/openshift4/dpdk-base-rhel8:v4.9.0-7
